### ISSUE TITLE
Image / container customization

### ISSUE THREAD

**Issue by lunitaris** [chimbosonic/hagrid-container#3]
Hello, 

I am trying to get hagrid GPG keyserver  into podman container.
This is the first time I am using podman of my life! (But I am no noob, so I will learn).

I discovered your work on github, it's exactly what I wanna do!
So Very nice, thank you in advance, I am trying to re-use your work!

---

So far for now

1) I cloned your repo.
2) As I am using podman and not docker but cmds are the same I did a :
`ln -s /usr/bin/podman /usr/bin/docker`

3) Building the project
`make && make build`

```
$ podman-images
localhost/hagrid.    TAG: dev-XXXXX
localhost/hagrid.    TAG: latest-dev
<none>
docker.io/library/rust 
```

4) **Now, what?**

Should I need to tweak the image before buidling it so the container will have my customized configuration files?

What are the files to tweak if I want to customize everything and replace defaults url and values with the url of the server?

I'd like to have some tips, which files are responsible for X or Y, and how to customize this image (web / mails / default values etc).

Thx in advance!

**Comment by chimbosonic** [comment]
As explained in the `README.md` you can start the container with 
```bash
docker run --rm -it -p 8080:8080\
	-v $(shell pwd)/data:/var/lib/hagrid\
	chimbosonic/hagrid:latest
```

Now since you are building it locally you can change `chimbosonic/hagrid:latest` with `localhost/hagrid:latest-dev`

As for how to customise it the entrypoint will generate the default config in the `/var/lib/hagrid` folder inside the container.
To modify or persist the config you can mount that. In the command above we mount it to the current directory under a folder called `data` see `-v $(shell pwd)/data:/var/lib/hagrid\`. That will contain the `Rocket.toml` that has the hagrid config as well as things like the default webpages.

Hope this helps
