### ISSUE TITLE
Customization of volumes

### ISSUE THREAD

**Issue by lunitaris** [chimbosonic/hagrid-container#4]
Hello, I am having issues to customize mounted volumes with this container.

I am running podman (cmds are the same as docker).
I did a symlink on podman --> docker, so system can use docker command to use podman.

As a nromal user, I built the container.
Then, created folders in $HOME, **that will only contains keys:**
- /var/lib/hagrid/keys
- /var/lib/hagrid/public/keys
`mkdir -p $HOME/Hagrid_keys/internal $HOME/Hagrid_keys/public`

Then, run the container:
`podman run -d -p 8080:8080 --volume $HOME/Hagrid_keys/internal:/var/lib/hagrid/keys:Z --volume $HOME/Hagrid_keys/public:/var/lib/hagrid/public/keys:Z localhost/hagrid-tehtrix:latest-dev -e port=8080`

My issue is: 
I can't upload keys when I am using this cmdline.
If I don't mount the hole /var/lib/hagrid/ folder of the container, I am unable to upload keys.

i don't know what is the issue... Of course, I don't have any logs ^^
Can you help me?
Do you know how to setup Hagrid to display DEBUG verbose logs so I can see what's going on?

**Comment by chimbosonic** [comment]
So I don't know how to get Hagrid to debug I would ask in [upstream](https://gitlab.com/keys.openpgp.org/hagrid)

As for the folders do you need to mount them separately?  Also a guess would be that hagrid will not be run as root due to it being launched by podman so you might need to change permissions on those folders.
